### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by AlphaKR93** [PrismarineTeam/.github#1]
- [x] Purpur & Pufferfish 동시 자동 업스트림 추가
- [x] 동시커밋 픽스 (커밋 전 체크)
- [x] Purpur 업스트림때 Pufferfish 업스트림 안함
